### ISSUE TITLE
arm 启动失败 standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by AboutCXJ** [ClassmateLin/scripts_v2#3]
<img width="780" alt="截屏2022-01-15 23 13 30" src="https://user-images.githubusercontent.com/19811825/149626867-b2a3ad45-3998-41ee-a830-96a8e2faddf6.png">

<img width="832" alt="截屏2022-01-15 23 15 28" src="https://user-images.githubusercontent.com/19811825/149626904-d8aec39d-89fc-4e43-8cc9-9da5f2023440.png">

**Comment by ClassmateLin** [comment]
docker pull classmatelin/scripts_v2:arm64
