### ISSUE TITLE
关于脚本数量

### ISSUE THREAD

**Issue by ayuayue** [ClassmateLin/scripts_v2#6]
之前的python版本脚本比较多，go版的是只有这些脚本吗还是目前暂时只重写了这些

**Comment by ClassmateLin** [comment]
本版本设计不仅仅支持jd的脚本, 可支持多平台。后续有空会增加脚本数量

**Comment by ayuayue** [comment]
> 本版本设计不仅仅支持jd的脚本, 可支持多平台。后续有空会增加脚本数量

感谢回复
